meta:
  name: "난방 설정"
  name_en: "Heaters"
  description: "코콤 TheArt 난방 온도조절기 설정입니다. 난방 개수를 설정할 수 있습니다. 외출 모드를 지원합니다."
  description_en: "Kocom TheArt heating thermostats with away preset mode. Configurable count."
  version: "2.0.1"
  author: "wooooooooooook"
  tags: ["climate", "heater", "thermostat", "kocom", "theart"]

parameters:
  - name: heater_count
    type: integer
    default: 5
    min: 1
    max: 8
    label: "난방 개수"
    label_en: "Number of Heaters"

discovery:
  match:
    data: [0x30, 0xd0, 0x00, 0x36]
    mask: [0xFF, 0xFF, 0xFF, 0xFF]

entities:
  climate:
    - $repeat:
        count: '{{heater_count}}'
        as: i
        start: 1
      id: 'room_{{i - 1}}_heater'
      name: 'Room {{i - 1}} Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, '{{i - 1}}']
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 14
        length: 1
        precision: 0
      state_temperature_target:
        offset: 12
        length: 1
        precision: 0
      state_off:
        offset: 10
        data: [0x00]
        mask: [0xf0]
      state_heat:
        offset: 10
        data: [0x10]
        mask: [0xf0]
      state_preset_away:
        offset: 11
        data: [0x01]
      state_preset_none:
        offset: 11
        data: [0x00]
      
      # TheArt Cmd: [[..., index, 0x01, 0x00, 0x00, mode(0x00?), 0x00, target...]]
      # command_off: mode 0x00 (byte 8), byte 9=0x00
      # command_heat: mode 0x11, byte 9=0x00
      # command_preset_away: mode 0x11, byte 9=0x01
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x36, '{{i - 1}}', 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x36, '{{i - 1}}']]
      command_heat: >-
        [[0x30, 0xbc, 0x00, 0x36, '{{i - 1}}', 0x01, 0x00, 0x00, 0x11, 0x00, target, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x36, '{{i - 1}}']]
      command_preset_none: >-
        [[0x30, 0xbc, 0x00, 0x36, '{{i - 1}}', 0x01, 0x00, 0x00, 0x11, 0x00, target, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x36, '{{i - 1}}']]
      command_preset_away: >-
        [[0x30, 0xbc, 0x00, 0x36, '{{i - 1}}', 0x01, 0x00, 0x00, 0x11, 0x01, target, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x36, '{{i - 1}}']]
      command_temperature: >-
        [[0x30, 0xbc, 0x00, 0x36, '{{i - 1}}', 0x01, 0x00, 0x00, 0x11, 0x00, target, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x36, '{{i - 1}}']]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x36, '{{i - 1}}', 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc, 0x00, 0x36, '{{i - 1}}']
        
automation:
  - $repeat:
      count: '{{heater_count}}'
      as: i
      start: 1
    id: 'heater_{{i - 1}}_refresh'
    trigger:
      - type: schedule
        every: 2h
    then:
      - action: command
        target: id(room_{{i - 1}}_heater).command_update()
