meta:
  name: "거실 조명 설정 (3개)"
  name_en: "Living Room Lights (3 Lights)"
  description: "코콤 Theart 거실 조명 3개 설정입니다."
  description_en: "Kocom Theart living room with 3 lights."
  version: "1.0.1"
  author: "wooooooooooook"
  tags: ["light", "kocom", "theart", "livingroom"]

entities:
  light:
    - id: 'livingroom_light_1'
      name: 'Livingroom Light 1'
      state:
        data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_on:
        offset: 8
        data: [0xff]
      state_off:
        offset: 8
        data: [0x00]
      command_on: >-
        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, 0xff, states['livingroom_light_2']['state'] == 'ON' ? 0xff : 0x00, states['livingroom_light_3']['state'] == 'ON' ? 0xff : 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x0e, 0x00]]
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, 0x00, states['livingroom_light_2']['state'] == 'ON' ? 0xff : 0x00, states['livingroom_light_3']['state'] == 'ON' ? 0xff : 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x0e, 0x00]]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc, 0x00, 0x0e, 0x00]

    - id: 'livingroom_light_2'
      name: 'Livingroom Light 2'
      state:
        data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_on:
        offset: 9
        data: [0xff]
      state_off:
        offset: 9
        data: [0x00]
      command_on: >-
        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, states['livingroom_light_1']['state'] == 'ON' ? 0xff : 0x00, 0xff, states['livingroom_light_3']['state'] == 'ON' ? 0xff : 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x0e, 0x00]]
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, states['livingroom_light_1']['state'] == 'ON' ? 0xff : 0x00, 0x00, states['livingroom_light_3']['state'] == 'ON' ? 0xff : 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x0e, 0x00]]

    - id: 'livingroom_light_3'
      name: 'Livingroom Light 3'
      state:
        data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_on:
        offset: 10
        data: [0xff]
      state_off:
        offset: 10
        data: [0x00]
      command_on: >-
        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, states['livingroom_light_1']['state'] == 'ON' ? 0xff : 0x00, states['livingroom_light_2']['state'] == 'ON' ? 0xff : 0x00, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x0e, 0x00]]
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, states['livingroom_light_1']['state'] == 'ON' ? 0xff : 0x00, states['livingroom_light_2']['state'] == 'ON' ? 0xff : 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc, 0x00, 0x0e, 0x00]]

automation:
  - id: 'lights_refresh'
    trigger:
      - type: schedule
        every: 2h
    then:
      - action: command
        target: id(livingroom_light_1).command_update()
