meta:
  name: "현관문세트"
  name_en: "Doorbell Set"
  description: "현대 이마주 현관문세트 설정입니다. 개인현관문과 공동현관문의 벨 감지, 통화, 문열기 기능을 지원합니다. 주방폰에 baud_rate 3880으로 연결이 필요하다고 생각됩니다."
  description_en: "Hyundai Imazu doorbell set configuration. Supports bell detection, calling, and door opening for private and common entrances. It is thought that it needs to connect to the kitchen phone with baud_rate 3880."
  version: "2.0.0"
  min_version: "1.16.0"
  author: "blank-page-1203"
  tags: ["doorbell", "hyundai", "switch", "button"]

# 패킷 프로토콜 설명:
# (W: Wallpad, S: Sub 주방폰)
#
# 7F B4 00 00 EE // W <- S 문열림 (통화중에만 가능)
#
# 7F B5 00 00 EE // W -> S 현관 문 호출
# 7F B6 00 00 EE // W -> S 현관 문 호출 끝
#
# 7F B9 00 00 EE // W <- S 통화 열기 (주방폰 발신)
# 7F BA 00 00 EE // W <- S 통화 열기 끝 (주방폰 발신)
#
# 7F BB 00 00 EE // W -> S 다른 통화가 있음
#
# 7F B7 00 00 EE // W <- S 통화 수신
# 7F B8 00 00 EE // W <- S 통화 종료
#
# 7F 5A 00 00 EE // W -> S 공동현관문 호출
# 7F 5C 00 00 EE // W -> S 공동현관문 호출 끝
#
# 7F 5F 00 00 EE // W <- S 공동현관문 호출 수신
#
# 7F 61 00 00 EE // W <- S 공동현관문 열기 (통화중에만 가능)
# 7F 60 00 00 EE // W <- S 통화 종료
#
# 호출이 온 경우 문을 열려면:
# 7F B7 00 00 EE // W <- S 통화 수신
# 7F B4 00 00 EE // W <- S 문열림
# 7F B8 00 00 EE // W <- S 통화 종료
#
# 통화 없이 문을 열려면:
# 7F B9 00 00 EE // W <- S 통화 열기 (주방폰 발신)
# 7F B4 00 00 EE // W <- S 문열림
# 7F BA 00 00 EE // W <- S 통화 열기 끝 (주방폰 발신)
#
# 공동현관문은 통화 없이는 문을 열 수 없기에 외부에서 호출이 와야만 열 수 있습니다.
# 7F 5F 00 00 EE // W <- S 공동현관문 호출 수신
# 7F 61 00 00 EE // W <- S 공동현관문 열기 (통화중에만 가능)
# 7F 60 00 00 EE // W <- S 통화 종료

scripts:
  - id: answer_front_doorbell
    description: Answer front doorbell
    mode: single
    actions:
      - action: send_packet
        data: [0xB7, 0x00, 0x00]
        header: true
        footer: true
      - action: if
        condition: get_from_states('front_doorbell', 'state', 'OFF') == 'ON'
        then:
          - action: update_state
            target_id: front_doorbell
            state:
              state: 'OFF'
  - id: answer_lobby_doorbell
    description: Answer lobby doorbell
    mode: single
    actions:
      - action: send_packet
        data: [0x5F, 0x00, 0x00]
        header: true
        footer: true
      - action: if
        condition: get_from_states('lobby_doorbell', 'state', 'OFF') == 'ON'
        then:
          - action: update_state
            target_id: lobby_doorbell
            state:
              state: 'OFF'
  - id: open_front_door_script
    description: Open front door when called
    mode: single
    actions:
      - action: command
        target: id(call_front_doorbell).command_on()
      - action: delay
        milliseconds: 230
      - action: send_packet
        data: [0xB4, 0x00, 0x00]
        header: true
        footer: true
      - action: delay
        milliseconds: 2500
      - action: command
        target: id(call_front_doorbell).command_off()
  - id: open_front_door_in_house_script
    description: Open front door in house without call
    mode: single
    actions:
      - action: command
        target: id(call_front_doorbell_in_house).command_on()
      - action: delay
        milliseconds: 230
      - action: send_packet
        data: [0xB4, 0x00, 0x00]
        header: true
        footer: true
      - action: delay
        milliseconds: 2500
      - action: command
        target: id(call_front_doorbell_in_house).command_off()
  - id: open_lobby_door_script
    description: Open lobby door when called
    mode: single
    actions:
      - action: command
        target: id(call_lobby_doorbell).command_on()
      - action: delay
        milliseconds: 230
      - action: send_packet
        data: [0x61, 0x00, 0x00]
        header: true
        footer: true
      - action: delay
        milliseconds: 2500
      - action: command
        target: id(call_lobby_doorbell).command_off()
binary_sensor:
  - id: front_doorbell
    name: front_doorbell
    icon: mdi:bell-ring
    state:
      data: [0xB4, 0x00, 0x00]
      mask: [0x00, 0xFF, 0xFF]
    state_on:
      offset: 1
      data: [0xB5]
    state_off: data[1] == 0xB6 || data[1] == 0xB7
    type: binary_sensor
    unique_id: homenet_hyundai_imazu_doorbell_front_doorbell
    discovery_always: true
  - id: lobby_doorbell
    name: lobby_doorbell
    icon: mdi:bell-ring
    state:
      data: [0x58, 0x00, 0x00]
      mask: [0xF0, 0xFF, 0xFF]
    state_on:
      offset: 1
      data: [0x5A]
    state_off: data[1] == 0x5C || data[1] == 0x5F
    type: binary_sensor
    unique_id: homenet_hyundai_imazu_doorbell_lobby_doorbell
    discovery_always: true
button:
  - id: open_front_door
    name: open_front_door
    icon: mdi:door-sliding-open
    command_press:
      script: open_front_door_script
    type: button
    unique_id: homenet_hyundai_imazu_doorbell_open_front_door
    discovery_always: true
  - id: open_front_door_in_house
    name: open_front_door_in_house
    icon: mdi:door-sliding-open
    command_press:
      script: open_front_door_in_house_script
    type: button
    unique_id: homenet_hyundai_imazu_doorbell_open_front_door_in_house
    discovery_always: true
  - id: open_lobby_door
    name: open_lobby_door
    icon: mdi:door-sliding-open
    command_press:
      script: open_lobby_door_script
    type: button
    unique_id: homenet_hyundai_imazu_doorbell_open_lobby_doorbell
    discovery_always: true
switch:
  - id: call_front_doorbell
    name: call_front_doorbell
    icon: mdi:phone
    command_on:
      script: answer_front_doorbell
    command_off:
      data: [0xB8, 0x00, 0x00]
    packet_parameters:
      tx_retry_cnt: 0
    type: switch
    unique_id: homenet_hyundai_imazu_doorbell_call_front_doorbell
    discovery_always: true
  - id: call_front_doorbell_in_house
    name: call_front_doorbell_in_house
    icon: mdi:phone
    command_on:
      data: [0xB9, 0x00, 0x00]
    command_off:
      data: [0xBA, 0x00, 0x00]
    packet_parameters:
      tx_retry_cnt: 0
    type: switch
    unique_id: homenet_hyundai_imazu_doorbell_call_front_doorbell_in_house
    discovery_always: true
  - id: call_lobby_doorbell
    name: call_lobby_doorbell
    icon: mdi:phone
    command_on:
      script: answer_lobby_doorbell
    command_off:
      data: [0x60, 0x00, 0x00]
    packet_parameters:
      tx_retry_cnt: 0
    type: switch
    unique_id: homenet_hyundai_imazu_doorbell_call_lobby_doorbell
    discovery_always: true
  - id: auto_open_front_door
    name: auto_open_front_door
    icon: mdi:door-open
    optimistic: true
    type: switch
    unique_id: homenet_hyundai_imazu_doorbell_auto_open_front_door
  - id: auto_open_lobby_door
    name: auto_open_lobby_door
    icon: mdi:door-open
    optimistic: true
    type: switch
    unique_id: homenet_hyundai_imazu_doorbell_auto_open_lobby_door
automation:
  - id: auto_open_front_door_automation
    mode: single
    trigger:
      - type: state
        entity_id: front_doorbell
        property: state
        match:
          eq: 'ON'
    guard: get_from_states('auto_open_front_door', 'state', 'OFF') == 'ON'
    then:
      - action: delay
        milliseconds: 1000
      - action: script
        script: open_front_door_script
  - id: auto_open_lobby_door_automation
    mode: single
    trigger:
      - type: state
        entity_id: lobby_doorbell
        property: state
        match:
          eq: 'ON'
    guard: get_from_states('auto_open_lobby_door', 'state', 'OFF') == 'ON'
    then:
      - action: delay
        milliseconds: 1000
      - action: script
        script: open_lobby_door_script
  - id: front_doorbell_off_automation
    mode: single
    trigger:
      - type: state
        entity_id: front_doorbell
        property: state
        match:
          eq: 'ON'
    then:
      - action: delay
        milliseconds: 30000
      - action: if
        condition: get_from_states('front_doorbell', 'state', 'OFF') == 'ON'
        then:
          - action: update_state
            target_id: front_doorbell
            state:
              state: 'OFF'
  - id: lobby_doorbell_off_automation
    mode: single
    trigger:
      - type: state
        entity_id: lobby_doorbell
        property: state
        match:
          eq: 'ON'
    then:
      - action: delay
        milliseconds: 30000
      - action: if
        condition: get_from_states('lobby_doorbell', 'state', 'OFF') == 'ON'
        then:
          - action: update_state
            target_id: lobby_doorbell
            state:
              state: 'OFF'