meta:
  name: "난방 설정"
  name_en: "Heaters"
  description: "현대 이마주 난방 설정입니다. 난방 개수를 설정할 수 있습니다. 외출 모드를 지원합니다."
  description_en: "Hyundai Imazu heating configuration with count parameter. Supports away mode."
  version: "2.1.0"
  author: "wooooooooooook"
  tags: ["climate", "heater", "thermostat", "hyundai", "imazu"]
  min_version: "2.2.0"

parameters:
  - name: heater_count
    type: integer
    default: 5
    min: 1
    max: 8
    label: "난방 개수"
    label_en: "Number of Heaters"

discovery:
  match:
    data: [0x00, 0x01, 0x18, 0x04, 0x45]
    mask: [0x00, 0xff, 0xff, 0xff, 0xff]

entities:
  climate:
    - $repeat:
        count: '{{heater_count}}'
        as: i
        start: 1
      id: 'heater_{{i}}'
      name: 'Heater {{i}}'
      visual:
        min_temperature: 5 °C
        max_temperature: 40 °C
        temperature_step: 1 °C
      state:
        data: [0x00, 0x01, 0x18, 0x04, 0x45, '{{0x10 + i - 1}}']
        mask: [0x00, 0xff, 0xff, 0xff, 0xfc, 0xff]
      state_temperature_current:
        offset: 9
        length: 1
        precision: 0
      state_temperature_target:
        offset: 10
        length: 1
        precision: 0
      state_off:
        offset: 8
        data: [0x04]
      state_heat:
        offset: 8
        data: [0x01]
      state_preset_away:
        offset: 8
        data: [0x07]
      state_preset_none:
        offset: 8
        data: [0x07]
        inverted: True
      
      command_off:
        data: [0x0B, 0x01, 0x18, 0x02, 0x46, '{{0x10 + i - 1}}', 0x04, 0x00]
        ack: [0x0D, 0x01, 0x18, 0x04, 0x46, '{{0x10 + i - 1}}', 0x04, 0x04]
      command_heat:
        data: [0x0B, 0x01, 0x18, 0x02, 0x46, '{{0x10 + i - 1}}', 0x01, 0x00]
        ack: [0x0D, 0x01, 0x18, 0x04, 0x46, '{{0x10 + i - 1}}', 0x01, 0x01]
      command_preset_away:
        data: [0x0B, 0x01, 0x18, 0x02, 0x46, '{{0x10 + i - 1}}', 0x07, 0x00]
        ack: [0x0D, 0x01, 0x18, 0x04, 0x46, '{{0x10 + i - 1}}', 0x07, 0x07]
      command_preset_none:
        data: [0x0B, 0x01, 0x18, 0x02, 0x46, '{{0x10 + i - 1}}', 0x01, 0x00]
        ack: [0x0D, 0x01, 0x18, 0x04, 0x46, '{{0x10 + i - 1}}', 0x01, 0x01]
      command_temperature: >-
        [[0x0B, 0x01, 0x18, 0x02, 0x45, '{{0x10 + i - 1}}', x, 0x00],[0x0D, 0x01, 0x18, 0x04, 0x45, '{{0x10 + i - 1}}', x, 0x01]]

    # State Proxies for Periodic Updates
    - $repeat:
        count: '{{heater_count}}'
        as: i
        start: 1
      name: 'Heater {{i}} Proxy'
      state_proxy: true
      target_id: 'heater_{{i}}'
      state:
        # Full state response packet
        # F7 22 01 18 04 46 10 00 [H1_Stat] [H1_Cur] [H1_Tar] ...
        data: [0x00, 0x01, 0x18, 0x04, 0x46, 0x10, 0x00]
        mask: [0x00, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff]
      
      # Offsets calculation:
      # H1: 9, 10, 11
      # H2: 12, 13, 14
      # Gap = 3. 
      # Base = 9 + (i-1)*3
      
      state_heat:
        offset: '{{9 + (i-1)*3}}'
        data: [0x01]
      state_off:
        offset: '{{9 + (i-1)*3}}'
        data: [0x04]
      state_temperature_current:
        offset: '{{10 + (i-1)*3}}'
        length: 1
        precision: 0
      state_temperature_target:
        offset: '{{11 + (i-1)*3}}'
        length: 1
        precision: 0

automation:
  - id: 'request_heaters_state'
    trigger:
      - type: schedule
        every: 15m
    then:
      - action: send_packet
        # Request all heaters state
        data: [0x0B, 0x01, 0x18, 0x01, 0x46, 0x10, 0x00, 0x00]
        header: true
        footer: true
        checksum: true
