meta:
  name: "주기적 난방 상태요청 자동화"
  name_en: "Periodic climate state request automation"
  description: "!난방 설정에 통합되었습니다. 이걸 사용할 필요가 없습니다! 상태 갱신을 위한 주기적 난방 상태요청 자동화입니다."
  description_en: "Periodic climate state request automation for Hyundai Telecom wallpads."
  version: "1.0.0"
  author: "muuky"
  tags: ["hyundai", "imazu"]

automation:
    - id: 'send_heat_state_packet'
      trigger:
        - type: schedule
          every: 15m
      then:
        - action: send_packet # 난방
          data: [0x0B, 0x01, 0x18, 0x01, 0x46, 0x10, 0x00, 0x00]
          header: true
          checksum: true
          footer: true

    - id: 'update_heat'
      trigger:
        - type: packet
          match:
            # f7 22 01 18 04 46 10 00 
            # 01 17 18 -> 1번방 on / 현재 23도 / target 24도
            # 04 18 19 -> 2번방 off / 현재 24도 / target 25도
            # 04 16 18 -> 3번방 off / 현재 22도 / target 24도
            # 04 15 16 -> 4번방 off / 현재 21도 / target 22도
            # 00 00 00 00 00 00 00 00 00 00 00 00 98 ee
            data: [0x22, 0x01, 0x18, 0x04, 0x46, 0x10, 0x00]
            mask: [0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff]
      then:
        - action: update_state
          target_id: heater_1
          state:
            state_heat:
              offset: 9
              data: [0x01]
            state_off:
              offset: 9
              data: [0x04]
            state_temperature_current:
              offset: 10
              length: 1
              precision: 0
            state_temperature_target:
              offset: 11
              length: 1
              precision: 0
        - action: update_state
          target_id: heater_2
          state:
            state_heat:
              offset: 12
              data: [0x01]
            state_off:
              offset: 12
              data: [0x04]
            state_temperature_current:
              offset: 13
              length: 1
              precision: 0
            state_temperature_target:
              offset: 14
              length: 1
              precision: 0
        - action: update_state
          target_id: heater_3
          state:
            state_heat:
              offset: 15
              data: [0x01]
            state_off:
              offset: 15
              data: [0x04]
            state_temperature_current:
              offset: 16
              length: 1
              precision: 0
            state_temperature_target:
              offset: 17
              length: 1
              precision: 0
        - action: update_state
          target_id: heater_4
          state:
            state_heat:
              offset: 18
              data: [0x01]
            state_off:
              offset: 18
              data: [0x04]
            state_temperature_current:
              offset: 19
              length: 1
              precision: 0
            state_temperature_target:
              offset: 20
              length: 1
              precision: 0
            