import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Ajv from 'ajv';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { yamlConfigSchema } from '../src/lib/utils/yamlEditorConfig.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ajv = new Ajv({
  allErrors: true,
  strict: false,
  allowUnionTypes: true,
  code: {
    esm: true,
    source: true,
  },
});

const validate = ajv.compile(yamlConfigSchema);
const moduleCode = standaloneCode(ajv, validate);

const outputPath = path.resolve(
  __dirname,
  '../src/lib/utils/yamlConfigValidator.ts',
);

const banner = `/* eslint-disable */\n/* tslint:disable */\n// @ts-nocheck\n// This file is autogenerated by scripts/generateYamlSchemaValidator.js\n`;

await writeFile(outputPath, `${banner}${moduleCode}`);

console.log(`Generated ${outputPath}`);
