export const entityTypes: string[];
export const bridgeKeys: string[];
export const serialKeys: string[];
export const packetDefaultKeys: string[];
export const entityKeys: string[];
export const scriptKeys: string[];
export const automationKeys: string[];
export const serialValueSuggestions: Record<string, string[]>;
export const checksumSuggestions: string[];
export const entityConfigSchema: Record<string, unknown>;
export const scriptConfigSchema: Record<string, unknown>;
export const automationConfigSchema: Record<string, unknown>;
export const yamlConfigSchema: Record<string, unknown>;
