meta:
  name: "가스밸브 설정"
  name_en: "Gas Valve"
  description: "코콤 Thinks 가스밸브 설정입니다."
  description_en: "Kocom Thinks gas valve configuration."
  version: "1.0.1"
  author: "wooooooooooook"
  tags: ["valve", "gas", "kocom", "thinks"]

entities:
  valve:
    - id: 'gas_valve'
      name: 'Gas Valve'
      state:
        data: [0x30, 0xd0, 0x00, 0x2c, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_open:
        offset: 7
        data: [0x01]
      state_closed:
        offset: 7
        data: [0x01]
        inverted: true
      command_close:
        data: [0x30, 0xbc, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]

automation:
  - id: 'gas_valve_refresh'
    trigger:
      - type: schedule
        every: 2h
    then:
      - action: command
        target: id(gas_valve).command_update()
