meta:
  name: "난방 설정 (6개)"
  name_en: "Heaters (6 Thermostats)"
  description: "코콤 Thinks 난방 온도조절기 6개 설정입니다. (거실, Room 1-5)"
  description_en: "Kocom Thinks 6 heating thermostats with away preset mode."
  version: "1.0.1"
  author: "wooooooooooook"
  tags: ["climate", "heater", "thermostat", "kocom", "thinks"]

entities:
  climate:
    - id: 'livingroom_heater'
      name: 'Living Room Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x00]
        mask: [0xF0]
      state_heat:
        offset: 8
        data: [0x10]
        mask: [0xF0]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]

    - id: 'room_1_heater'
      name: 'Room 1 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x01]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]

    - id: 'room_2_heater'
      name: 'Room 2 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x02]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]

    - id: 'room_3_heater'
      name: 'Room 3 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x03]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]

    - id: 'room_4_heater'
      name: 'Room 4 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x04]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]

    - id: 'room_5_heater'
      name: 'Room 5 Heater'
      visual:
        min_temperature: 5 °C
        max_temperature: 30 °C
        temperature_step: 1 °C
      state:
        data: [0x30, 0xd0, 0x00, 0x36, 0x05]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_temperature_current:
        offset: 12
      state_temperature_target:
        offset: 10
      state_off:
        offset: 8
        data: [0x01]
      state_heat:
        offset: 8
        data: [0x11]
      state_preset_away:
        offset: 9
        data: [0x01]
      state_preset_none:
        offset: 9
        data: [0x00]
      command_off: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x01, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_heat: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_none: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_preset_away: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x11, 0x01, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_temperature: >-
        [[0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x00, 0x11, 0x00, x, 0x00, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x36, 0x05, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]

automation:
  - id: 'heaters_refresh'
    trigger:
      - type: schedule
        every: 2h
    then:
      - action: command
        target: id(livingroom_heater).command_update()
      - action: command
        target: id(room_1_heater).command_update()
      - action: command
        target: id(room_2_heater).command_update()
      - action: command
        target: id(room_3_heater).command_update()
      - action: command
        target: id(room_4_heater).command_update()
      - action: command
        target: id(room_5_heater).command_update()
