meta:
  name: "나비엔 환기팬 설정"
  name_en: "Navien Ventilator"
  description: "코콤 Thinks 나비엔 환기팬 설정입니다. 3단 속도를 지원합니다."
  description_en: "Kocom Thinks Navien ventilator with 3-speed control."
  version: "1.0.1"
  author: "wooooooooooook"
  tags: ["fan", "ventilation", "navien", "kocom", "thinks"]

entities:
  fan:
    - id: 'navien_ventilator'
      name: 'Navien Ventilator'
      state:
        data: [0x30, 0xd0, 0x00, 0x48, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_on:
        offset: 8
        data: [0x11]
      state_off:
        offset: 8
        data: [0x00]
      state_speed: >-
        if (data[10] === 0x40) 1
        if (data[10] === 0x80) 2
        if (data[10] === 0xc0) 3
        0
      command_on:
        data: [0x30, 0xbc, 0x00, 0x01, 0x00, 0x48, 0x00, 0x00, 0x11, 0x01, 0x40, 0x17, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]
      command_off:
        data: [0x30, 0xbc, 0x00, 0x01, 0x00, 0x48, 0x00, 0x00, 0x00, 0x01, 0x00, 0x17, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]
      command_speed: >-
        [[0x30, 0xbc, 0x00, 0x01, 0x00, 0x48, 0x00, 0x00, 0x11, 0x01, speed, 0x17, 0x00, 0x00, 0x00, 0x00], [0x30, 0xdc]]
      command_update:
        data: [0x30, 0xbc, 0x00, 0x48, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]

automation:
  - id: 'ventilator_refresh'
    trigger:
      - type: schedule
        every: 2h
    then:
      - action: command
        target: id(navien_ventilator).command_update()
