meta:
  name: "가스밸브 설정 (자동 갱신 포함)"
  name_en: "Gas Valve with Auto Polling"
  description: "가스밸브 엔티티와 상태 갱신 자동화가 포함된 설정입니다."
  description_en: "Gas valve entity with automatic status polling."
  version: "1.0.0"
  author: "wooooooooooook"
  tags: ["valve", "gas", "automation"]

entities:
  valve:
    - id: gas_valve
      name: 'Gas Valve'
      state:
        data: [0x30, 0xd0, 0x00, 0x2c, 0x00]
        mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
      state_open:
        offset: 7
        data: [0x01]
      state_closed:
        offset: 7
        data: [0x02]
      command_close:
        data: [0x30, 0xbc, 0x00, 0x2c, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
        ack: [0x30, 0xdc]

automation:
  - id: gas_valve_polling_1h
    trigger:
      - type: schedule
        every: 1h
    action:
      - type: command
        id: gas_valve
        command: command_update
