meta:
  name: "조명 설정"
  name_en: "Lights"
  description: "코콤 조명 설정입니다. 방별 조명 개수를 다르게 설정할 수 있습니다 (최대 4개). v1.15.0 이상에서 사용 가능합니다."
  description_en: "Kocom lights configuration. Configure light count per room (max 4). Available from v1.15.0."
  version: "2.1.0"
  author: "wooooooooooook"
  tags: ["light", "kocom"]
  min_version: "1.15.0"

parameters:
  - name: rooms
    type: object[]
    label: "방 설정"
    label_en: "Room Configuration"
    default:
      - room_idx: 0
        light_count: 3
      - room_idx: 1
        light_count: 2
      - room_idx: 2
        light_count: 2
      - room_idx: 3
        light_count: 2
    schema:
      room_idx:
        type: integer
        label: "방 번호"
        min: 0
        max: 15
      light_count:
        type: integer
        label: "조명 개수"
        default: 2
        min: 1
        max: 4

discovery:
  match:
    data: [0x30, 0xD0, 0x00, 0x0E]
    mask: [0xFF, 0xFF, 0xFF, 0xFF]
  dimensions:
    - parameter: "room_idx"
      offset: 6
  inference:
    strategy: "unique_tuples"
    output: "rooms"

automation:
  - id: 'query_all_lights'
    name: '모든 조명 상태 조회 (시작 시, 30분마다)'
    trigger:
      - type: startup
      - type: schedule
        every: 30m
    then:
      - $repeat:
          over: rooms
          as: room
        $nested:
          - action: send_packet
            data: [0x30, 0xBC, 0x00, 0x0E, '{{room.room_idx}}', 0x01, 0x00, 0x3A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
            ack:
              data: [0x30, 0xD0, 0x00, 0x0E, '{{room.room_idx}}']
              mask: [0xFF, 0xF0, 0xFF, 0xFF, 0xFF]

entities:
  light:
    - $repeat:
        over: rooms
        as: room
      $nested:
        # Light 1 (offset 8)
        - id: 'room_{{room.room_idx}}_light_1'
          name: 'Room {{room.room_idx}} Light 1'
          state:
            data: [0x30, 0xD0, 0x00, 0x0E, '{{room.room_idx}}']
            mask: [0xFF, 0xF0, 0xFF, 0xFF, 0xFF]
          state_on:
            offset: 8
            data: [0xFF]
          state_off:
            offset: 8
            data: [0x00]
          command_on: >-
            [[0x30, 0xBC, 0x00, 0x0E, {{room.room_idx}}, 0x01, 0x00, 0x00, 0xFF,
            has(states['room_{{room.room_idx}}_light_2']['state']) && states['room_{{room.room_idx}}_light_2']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_3']['state']) && states['room_{{room.room_idx}}_light_3']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_4']['state']) && states['room_{{room.room_idx}}_light_4']['state'] == 'ON' ? 0xFF : 0x00,
            0, 0, 0, 0], [0x30, 0xDC]]
          command_off: >-
            [[0x30, 0xBC, 0x00, 0x0E, {{room.room_idx}}, 0x01, 0x00, 0x00, 0x00,
            has(states['room_{{room.room_idx}}_light_2']['state']) && states['room_{{room.room_idx}}_light_2']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_3']['state']) && states['room_{{room.room_idx}}_light_3']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_4']['state']) && states['room_{{room.room_idx}}_light_4']['state'] == 'ON' ? 0xFF : 0x00,
            0, 0, 0, 0], [0x30, 0xDC]]

        # Light 2 (offset 9)
        - $if: '{{room.light_count}} >= 2'
          id: 'room_{{room.room_idx}}_light_2'
          name: 'Room {{room.room_idx}} Light 2'
          state:
            data: [0x30, 0xD0, 0x00, 0x0E, '{{room.room_idx}}']
            mask: [0xFF, 0xF0, 0xFF, 0xFF, 0xFF]
          state_on:
            offset: 9
            data: [0xFF]
          state_off:
            offset: 9
            data: [0x00]
          command_on: >-
            [[0x30, 0xBC, 0x00, 0x0E, {{room.room_idx}}, 0x01, 0x00, 0x00,
            has(states['room_{{room.room_idx}}_light_1']['state']) && states['room_{{room.room_idx}}_light_1']['state'] == 'ON' ? 0xFF : 0x00,
            0xFF,
            has(states['room_{{room.room_idx}}_light_3']['state']) && states['room_{{room.room_idx}}_light_3']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_4']['state']) && states['room_{{room.room_idx}}_light_4']['state'] == 'ON' ? 0xFF : 0x00,
            0, 0, 0, 0], [0x30, 0xDC]]
          command_off: >-
            [[0x30, 0xBC, 0x00, 0x0E, {{room.room_idx}}, 0x01, 0x00, 0x00,
            has(states['room_{{room.room_idx}}_light_1']['state']) && states['room_{{room.room_idx}}_light_1']['state'] == 'ON' ? 0xFF : 0x00,
            0x00,
            has(states['room_{{room.room_idx}}_light_3']['state']) && states['room_{{room.room_idx}}_light_3']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_4']['state']) && states['room_{{room.room_idx}}_light_4']['state'] == 'ON' ? 0xFF : 0x00,
            0, 0, 0, 0], [0x30, 0xDC]]

        # Light 3 (offset 10)
        - $if: '{{room.light_count}} >= 3'
          id: 'room_{{room.room_idx}}_light_3'
          name: 'Room {{room.room_idx}} Light 3'
          state:
            data: [0x30, 0xD0, 0x00, 0x0E, '{{room.room_idx}}']
            mask: [0xFF, 0xF0, 0xFF, 0xFF, 0xFF]
          state_on:
            offset: 10
            data: [0xFF]
          state_off:
            offset: 10
            data: [0x00]
          command_on: >-
            [[0x30, 0xBC, 0x00, 0x0E, {{room.room_idx}}, 0x01, 0x00, 0x00,
            has(states['room_{{room.room_idx}}_light_1']['state']) && states['room_{{room.room_idx}}_light_1']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_2']['state']) && states['room_{{room.room_idx}}_light_2']['state'] == 'ON' ? 0xFF : 0x00,
            0xFF,
            has(states['room_{{room.room_idx}}_light_4']['state']) && states['room_{{room.room_idx}}_light_4']['state'] == 'ON' ? 0xFF : 0x00,
            0, 0, 0, 0], [0x30, 0xDC]]
          command_off: >-
            [[0x30, 0xBC, 0x00, 0x0E, {{room.room_idx}}, 0x01, 0x00, 0x00,
            has(states['room_{{room.room_idx}}_light_1']['state']) && states['room_{{room.room_idx}}_light_1']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_2']['state']) && states['room_{{room.room_idx}}_light_2']['state'] == 'ON' ? 0xFF : 0x00,
            0x00,
            has(states['room_{{room.room_idx}}_light_4']['state']) && states['room_{{room.room_idx}}_light_4']['state'] == 'ON' ? 0xFF : 0x00,
            0, 0, 0, 0], [0x30, 0xDC]]

        # Light 4 (offset 11)
        - $if: '{{room.light_count}} >= 4'
          id: 'room_{{room.room_idx}}_light_4'
          name: 'Room {{room.room_idx}} Light 4'
          state:
            data: [0x30, 0xD0, 0x00, 0x0E, '{{room.room_idx}}']
            mask: [0xFF, 0xF0, 0xFF, 0xFF, 0xFF]
          state_on:
            offset: 11
            data: [0xFF]
          state_off:
            offset: 11
            data: [0x00]
          command_on: >-
            [[0x30, 0xBC, 0x00, 0x0E, {{room.room_idx}}, 0x01, 0x00, 0x00,
            has(states['room_{{room.room_idx}}_light_1']['state']) && states['room_{{room.room_idx}}_light_1']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_2']['state']) && states['room_{{room.room_idx}}_light_2']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_3']['state']) && states['room_{{room.room_idx}}_light_3']['state'] == 'ON' ? 0xFF : 0x00,
            0xFF, 0, 0, 0, 0], [0x30, 0xDC]]
          command_off: >-
            [[0x30, 0xBC, 0x00, 0x0E, {{room.room_idx}}, 0x01, 0x00, 0x00,
            has(states['room_{{room.room_idx}}_light_1']['state']) && states['room_{{room.room_idx}}_light_1']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_2']['state']) && states['room_{{room.room_idx}}_light_2']['state'] == 'ON' ? 0xFF : 0x00,
            has(states['room_{{room.room_idx}}_light_3']['state']) && states['room_{{room.room_idx}}_light_3']['state'] == 'ON' ? 0xFF : 0x00,
            0x00, 0, 0, 0, 0], [0x30, 0xDC]]
