meta:
  name: "현관문열림자동"
  name_en: "door auto open"
  description: "Ezville 현관문열림자동 설정입니다. 벨울림 -> 통화시작, 문열기, 통화종료를 순차전송 "
  description_en: "Ezville door auto open configuration. Bell ring -> call start, door open, call end in sequence."
  version: "1.0.0"
  author: "gunfos"
  tags: ["door auto open", "ezville"]

automation:
  - id: 'door_auto'
    trigger:
      - type: packet
        match:
          data: [0xf7, 0x40, 0x02, 0x93]
    then:
      # 통화 시작
      - action: send_packet
        data: [0xF7,0x40,0x02,0x12,0x00,0xA7,0xF2]
        checksum: false
      - action: delay
        milliseconds: 1000
      # 문열기
      - action: send_packet
        data:  [0xF7,0x40,0x02,0x22,0x00,0x97,0xF2]
        checksum: false
      - action: delay
        milliseconds: 1000
      # 통화 종료
      - action: send_packet
        data:  [0xF7,0x40,0x02,0x11,0x00,0xA4,0xEE]
        checksum: false
